epochs: 100
gene_dir: ./data/LGG/omics.csv
img_dir: ./data/LGG/pt_file
diagnostic_reports: ./data/LGG/reports.csv
best_model_path: ./results/LGG
sur_ret_dir: ./results/LGG
conch_ckpt: ./model/pytorch_model_CONCH.bin
schedule: [30, 60, 90]
opt: adamw
decay_epochs: 30
opt_eps: 1.0e-8
opt_no_filter: false
sgd_no_nesterov: false
dyrep: false
sched: cosine
decay_rate: 0.1
decay_by_epoch: false
model_ema: false
model_ema_decay: 0.99996
warmup_epochs: 0
warmup_lr: 5.0e-7
batch_size: 4
lr: 5.0e-4
min_lr: 1.0e-4
lr_decay: 0.1
gpu_id: "0"
momentum: 0.9
weight_decay: 1.0e-5
classes: 4
train_ration: 0.8
bag_loss: nll_surv
alpha_surv: 0.0
lambda_reg: 5.0e-6
vae_loss: 0.2
